Netflixclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('netflixapp.urls')),
    path('accounts/', include('allauth.urls')), 
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

netflixapp/urls.py
from django.urls import path 
from .views import Home ,ProfileList, ProfileCreate,MovieList,MovieDetail,PlayMovie,random_movie
from . import views 

app_name = 'netflixapp'

urlpatterns = [
    path("",Home.as_view(),name='Home'),
    path('profiles/',ProfileList.as_view(), name="profile-list"),
    path('profiles/create',ProfileCreate.as_view(),name="profile-create"),
    path('watch/<str:profile_id>/',MovieList.as_view(), name="movie-list"),
    path('watch/detail/<str:movie_id>/',MovieDetail.as_view(),name="movie-detail"),
    path('watch/play/<str:movie_id>/',PlayMovie.as_view(), name="play-movie"),
    path('random/',random_movie, name="random_movie"),
    path('logout/', views.custom_logout, name='custom_logout'),
]

netflixapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid 

# Create your models here.

AGE_CHOICES = (
    ('All','All'),
    ('Kids','Kids'),
)

MOVIE_CHOICES = (
    ('seasonal','Seasonal'),
    ('single', 'Single'),
)

class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('Profile', blank=True)

class Profile(models.Model):
    name = models.CharField(max_length=1000)
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)
    uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(choices=MOVIE_CHOICES, max_length=10)
    video = models.ManyToManyField('Video')
    image = models.ImageField(upload_to='covers')
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)
    
    def __str__(self):
        return self.title 
    

class Video(models.Model):
    title = models.CharField(max_length=1000)
    file = models.FileField(upload_to='movies')

    def __str__(self):
        return self.title

netflixapp/forms.py
from django.forms import ModelForm
from netflixapp.models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['uuid']

netflixapp/views.py
import imp 
import random 
from django.shortcuts import render,redirect,HttpResponse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ProfileForm
from .models import Profile, Movie
from django.contrib.auth import logout

# Create your views here.

# def Home(request):
#     return render(request, 'netflixapp/index.html')

class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('netflixapp:profile-list')
        return render(request,'index.html')

method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self,request,*args,**kwargs):

        profiles =request.user.profiles.all()
        context = {
            'profiles':profiles
        }
        return render(request, 'profilelist.html',context)    
    
method_decorator(login_required, name='dispatch')
# class ProfileCreate(View):
#     def get(self, request, *args, **kwargs):
#         form = ProfileForm()
#         context = {
#             'form': form
#         }
#         return render(request, 'profileCreate.html', context)

#     def post(self, request, *args, **kwargs):
#         form = ProfileForm(request.POST)
#         if form.is_valid():
#             profile = form.save(commit=False)
#             profile.save()
#             request.user.profiles.add(profile)
#             return redirect('netflixapp:profile-list')
#         context = {
#             'form': form
#         }
#         return render(request, 'profileCreate.html', context)
class ProfileCreate(View):
    def get(self,request,*args,**kwargs):
        form = ProfileForm()
        context = {
            'form':form
        }
        return render(request, 'profileCreate.html',context)
    
    def post(self, request,*args,**kwargs):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            profile = Profile.objects.create (**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect ('netflixapp:profile-list')
        context = {
            'form':form
        }
       
        return render(request, 'profileCreate.html',context)   

method_decorator(login_required, name='dispatch')
class MovieList(View):
    def get(self, request,profile_id, *args, **kwargs): 
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit= profile.age_limit)
            if profile not in request.user.profiles.all():
                return redirect ('netflixapp:profile-list')
            context = {
                'movies':movies
            }

            return render(request, 'movielist.html',context)  
        except Profile.DoesNotExist:
            return redirect ('netflixapp:profile-list')
    

def random_movie(request):
        total_movies = Movie.objects.count()
        random_index = random.randint(0, total_movies - 1)
        random_movie = Movie.objects.all()[random_index]

        return render(request, 'movielist.html', {'random_movie': random_movie})



@method_decorator(login_required, name='dispatch')
class MovieDetail(View):
    def get(self, request,movie_id, *args, **kwargs): 
        try:
            movie = Movie.objects.get(uuid = movie_id)
            
            context = {
                'movie':movie
            }

            return render(request, 'moviedetail.html',context)  
        except Movie.DoesNotExist:
            return redirect ('netflixapp:profile-list')
        

@method_decorator(login_required, name='dispatch')
class PlayMovie(View):
    def get(self, request,movie_id, *args, **kwargs): 
        try:
            movie = Movie.objects.get(uuid = movie_id)
            movie = movie.video.values()
            
            context = {
                'movie':list(movie)
            }

            return render(request, 'playmovie.html',context)  
        except Movie.DoesNotExist:
            return redirect ('netflixapp:profile-list')


# def random_movie(request):
#     # Get the total number of movies in the database
#     total_movies = Movie.objects.count()

#     # Generate a random index
#     random_index = random.randint(0, total_movies - 1)

#     # Get the random movie
#     random_movie = Movie.objects.all()[random_index]

#     # Render the 'moviedetail.html' template with the random_movie context
#     return render(request, 'movielist.html', {'random_movie': random_movie})

# def random_movie(request):
#     if 'random_movie' not in request.session:
#         total_movies = Movie.objects.count()
#         random_index = random.randint(0, total_movies - 1)
#         random_movie = Movie.objects.all()[random_index]
#         request.session['random_movie'] = random_movie.id

#     return render(request, 'movielist.html', {'random_movie': request.session.get('random_movie')})



# def random_movie(request):
#     # Check if the request path is for the 'movielist.html' URL
#     if request.path == 'http://127.0.0.1:8080/watch/f3a59b40-b42f-40c9-8dc0-2b8639bf06be/':
#         # Get the total number of movies in the database
#         total_movies = Movie.objects.count()

#         # Generate a random index
#         random_index = random.randint(0, total_movies - 1)

#         # Get the random movie
#         random_movie = Movie.objects.all()[random_index]

#         # Render the 'movielist.html' template with the random_movie context
#         return render(request, 'movielist.html', {'random_movie': random_movie})

#     # If the request path is not for 'movielist.html', return a different response
#     return HttpResponse("This is a different page.")




def custom_logout(request):
    logout(request)
    return redirect('netflixapp:Home')

Netflixclone/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</head>
<body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Logout
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </a>
            {% endif %}
        </div>
    </nav>
    
    {% block content %}

    {% endblock content %}

    <footer class=" px-5 py-10" >
        <ul class="flex justify-between items-center">
            
            <li>&copy; All Rights Reserved | 2023</li>
            <li> Netflix Clone</li>
            <li>By: Okoye Francis </li>
        </ul>
    </footer>
        
</body>
</html>

Netflixclone/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main-container">
    <header class= "min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('/static/assets/background_netflix.jpg');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Unlimited movies, TV shows, and more.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Watch anywhere. Cancel anytime.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Ready to watch? Enter your email to create or restart your membership.
            </h4>
            
            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <input type="email" name="" id="" placeholder="Email address" class="md:py-5 py-4 px-2 placeholder-gray-500 rounded-tl-sm rounded-bl-sm outline-none  text-gray-900 bg-gray-50 block w-8/12 md:w-3/4">
                    <button class="bg-primary_red font-medium md:font-normal md:w-1/4 flex justify-center items-center py-4 px-1 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl">
                        <span>
                            Get Started
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                    </button>
                </div>
            </div>
        </div>
    </header>
</div>

    
    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'assets/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center order-2'>
            <img src="{% static 'assets/mobile-0819.jpeg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
        
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
     <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Watch Everywhere.
        </h2>
        <h5 class="md:text-xl text-lg">
            Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.
        </h5>
     </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'assets/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <div class="ccontainer">
        <h1 class="heading">Frequently Asked Questions </h1>
           
           <div class="accordion-container">
               
               <div class="accordion active">
                   <div class="accordion-heading">
                       <h3 class="H3">What is Netflix?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       Netflix is a streaming service that offers a wide variety of award-winning TV shows, 
                       movies, anime, documentaries, and more on thousands of internet-connected devices.
                       <br>
                       <br>
                       You can watch as much as you want, whenever you want without a single commercial - all 
                       for one low monthly price. There's always something new to discover and new TV shows and movies are added every week!
                   </p>
               </div>
               
               <div class="accordion">
                   <div class="accordion-heading">
                       <h3 class="H3">How much does Netflix cost?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. 
                       Plans range from ₦1,200 to ₦4,400 a month. No extra costs, no contracts.
                   </p>
               </div>
               
               <div class="accordion">
                   <div class="accordion-heading">
                       <h3 class="H3">Where can i watch?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal 
                       computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.
                       <br>
                       <br>
                       You can also download your favorite shows with the iOS, Android, or Windows 10 app. Use downloads to watch while you're on the go and without an internet connection. Take Netflix with you anywhere.
                   </p>
               </div>
               
               <div class="accordion">
                   <div class="accordion-heading">
                       <h3 class="H3">How do i cancel?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       Netflix is flexible. There are no pesky contracts and no commitments. You can easily cancel your account online in two clicks. 
                       There are no cancellation fees - start or stop your account anytime.
                   </p>
               </div>
               
               <div class="accordion">
                   <div class="accordion-heading">
                       <h3 class="H3">What can i watch on Netflix?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.
                   </p>
               </div>
               
               <div class="accordion">
                   <div class="accordion-heading">
                       <h3 class="H3">Is Netflix good for kids?</h3>
                       <i class="fas fa-angle-down"></i>
                   </div>
                   <p class="accordion-content">
                       The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows 
                       and movies in their own space.
                       <br>
                       <br>
                       Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating 
                       of content kids can watch and block specific titles you don’t want kids to see.
                   </p>
               </div>
           </div>
   </div>
   <hr>


<!-- <script>
let accordions = document.querySelectorAll('.accordion-container.accordion');

   accordions.forEach(acco =>{
       acco.onclick = () =>{
           acco.classList.add('active');
       }
   })
</script> -->

<!-- <script>
// Select all elements with the class "accordion"
let accordions = document.querySelectorAll('.accordion');

// Add a click event listener to each accordion element
accordions.forEach(acco => {
   acco.addEventListener('click', () => {
       accordions.forEach(subAcco =>{subAcco.classList.remove('active')});
       // Toggle the "active" class on the clicked accordion
       acco.classList.toggle('active');
   });
});
</script> -->

<script>
   // Select all elements with the class "accordion"
   let accordions = document.querySelectorAll('.accordion');
   
   // Add a click event listener to each accordion element
   accordions.forEach(acco => {
       acco.addEventListener('click', () => {
           // Check if the clicked accordion is active (expanded)
           const isActive = acco.classList.contains('active');
           
           // Remove the "active" class from all accordions
           accordions.forEach(accordion => {
               accordion.classList.remove('active');
           });
   
           // If the clicked accordion was not active, make it active (expand)
           if (!isActive) {
               acco.classList.add('active');
           }
       });
   });
   </script>
{% endblock content%}

Netflixclone/templates/moviedetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{{ movie.image.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4" style="font-weight: bolder;">
                    {{movie.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{movie.description}}
                </p>
                <div class="flex my-4">

                    <a href="{% url 'netflixapp:play-movie' movie_id=movie.uuid %}" class="flex items-center bg-black py-2 px-5 rounded-md">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </a>
    
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                      {{movie.description}}
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>
{% endblock content %}

Netflixclone/templates/movielist.html
{% extends 'base.html' %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
</head>

{% block content %}
    <!-- <main class=' min-h-screen w-full'>

        <section class="vikings h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image:  url('/static/assets/vikings.jpeg');">
            
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    <h3>Vikings </h3>
                </h2>
                <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
                    <p></p>
                </p>
                <div class="flex my-4">
                    <button class="flex items-center bg-gray-500 py-2 px-5 rounded-md">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                    <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                        <ion-icon name="information-circle-outline" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            More Info
                        </span>
                    </button>
                </div>
            </div>
        </section>  -->

        <section class='bg-primary_black min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Popular on Netflix
                </h2>

                <div class="flex justify-center items-center min-w-full movie-lis">
                    <div class="flex flex-wrap justify-start -m-8">
                        {% for movie in movies %}
                        <a href="{% url 'netflixapp:movie-detail' movie_id=movie.uuid %}">
                            <div class="h-40 m-4 p-4 bg-blue-500 flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{movie.image.url}}" class="w-full h-full" alt="">
                                <!-- <p class="Lowercase">{{ movie.title }}</p> -->
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </section>
    </main>

    <script>
        window.addEventListener('load', function () {
            // Get the URL from the hidden div's data attribute
            var randomMovieUrl = document.getElementById('netflixapp:random-movie').getAttribute('data-url');
        });
        </script>
{% endblock content %}






    <!-- <div class="grid grid-rows-4 gap-4">
        {% for movie in movies %}
        <div class="w-1/6">

            <a href="{% url 'netflixapp:movie-detail' movie_id=movie.uuid %}">
                <div class=" h-40 m-4  bg-blue-500 flex-shrink-0 rounded-md cursor-pointer w-40 w-1/4">
                    <img src="{{movie.image.url}}" class="w-full h-full " alt="">
                </div>
            </a>
        </div>
        {% endfor %}
    </div> -->

Netflixclone/templates/playmovie.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black h-full w-full '>
        {{movie|json_script:'movie_data'}}
        <video src="" controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEL = document.querySelector('video')
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        const url = new URL(location.href)
        const video_param = parseInt(url.searchParams.get('epi'))?parseInt(url.searchParams.get('epi')):0
        videoEL.setAttribute('src',`http://localhost:8080/media/${movie_data[video_param].file}`)
    </script>
{% endblock content %}

Netflixclone/templates/profileCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="main-container">
    <section class=' min-h-screen py-20 md:py-32 flex-col flex items-center'>
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">{% csrf_token %}
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                       
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100" type="submit">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>
</div>
{% endblock content %}

Netflixclone/templates/profilelist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class=' min-h-screen py-20 md:py-0 flex-col flex justify-center items-center' style="background-image: url('assets/background_netflix.jpg');">
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>
        
        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
           {% for profile in profiles %}
           <a href="{% url 'netflixapp:movie-list' profile_id=profile.uuid %}">
                <div class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex">
                    <p class="text-6x3" style="font-weight:900;">{{ profile.name|slice:":1"}}</p>
                    <p>{{ profile.name}}</p>
                </div>
           </a>
           {% endfor %}
           
        </div>
        <div class="flex justify-center items-center">
            <a href="{% url 'netflixapp:profile-create' %}" class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                Add A New Profile
            </a>
        </div>
    </section>

{% endblock content %}